---
title: "Project proposal (SF2957)"
output: pdf_document
author: Benjamin Allévius, Sebastian Rosengren, Erik Thorsén
---

We aim to implement an \textbf{reinforcement learning} algorithm which can play the card game \textbf{blackjack}. Some of the recourses to be used are course material on reinforcement learning, the reference given by the project description https://arxiv.org/pdf/1603.01121.pdf as well as other literature such as http://cs.ou.edu/~granville/paper.pdf.

A short outline of what the project will include, but is not limited to, is presented below.
\begin{enumerate}
\item A working reinforcement algorithm which is able to play blackjack using the existing blackjack libraries, ex. OpenAI Gym: https://github.com/dennybritz/reinforcement-learning/blob/master/lib/envs/blackjack.py.
\item Code in Python 3.6 together with tensorflow whenever possible.
\item A public GitHub repository available for future participants to work with.
\end{enumerate}

Our initial goal is to read up on various reinforcement learning algorithms
and choose one to implement. Once implemented and trained, we will compare its 
performance to theoretical bounds for blackjack. \textbf{If time permits}, we 
will also try to implement other reinforcement learning algorithms, compare the 
performance of all algorithms, and see if we can apply \emph{ensemble learning}
to combine the algorithms into one. 
